<?php
require 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// Initialize dompdf without specific options
$dompdf = new Dompdf();

// Load HTML content
$html = '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sample PDF</title>
  <style>
    body {
      font-family: Arial, sans-serif;
    }
    h1 {
      font-family: "Courier New", Courier, monospace;
    }
  </style>
</head>
<body>
<h1>Hello, World!</h1>
<p>This is a sample PDF generated by dompdf.</p>
</body>
</html>
';

$dompdf->loadHtml($html);

// Set paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream("sample.pdf", array("Attachment" => false));